Repository llamastack/llama-stack-k8s-operator, pull requests merged in 2025-07, with the labels that each got.

#82 feat(cd): gh workflow to automate release creation
  .github/workflows/generate-release.yml
  Makefile
  README.md
Labels: enhancement, exciting stuff!

#100 feat(cli): enable selective test execution in make test
  CONTRIBUTING.md
  Makefile
Labels: documentation, enhancement, exciting stuff!

#98 chore: Add LICENSE
  LICENSE
Labels: do-not-merge

#118 refactor(field_mutator): migrate dot notation to JSON Pointer syntax
  pkg/deploy/kustomizer.go
  pkg/deploy/plugins/field_mutator.go
  pkg/deploy/plugins/field_mutator_test.go
Labels: enhancement, exciting stuff!

#113 feat(kustomizer): add service comparison and immutability enforcement utilities
  pkg/compare/comparison.go
  pkg/compare/comparison_test.go
Labels: enhancement, exciting stuff!

#121 refactor(controller): add anti-fragile test patterns and clean up utilities
  CONTRIBUTING.md
  controllers/llamastackdistribution_controller_test.go
  controllers/suite_test.go
  controllers/testing_support_test.go
Labels: documentation, exciting stuff!

#105 feat(controller): migrate service reconciliation to kustomize manifest
  controllers/llamastackdistribution_controller.go
  controllers/manifests/base/kustomization.yaml
  controllers/manifests/base/service.yaml
  pkg/deploy/deploy.go
  pkg/deploy/kustomizer.go
  pkg/deploy/kustomizer_test.go
Labels: enhancement, exciting stuff!
